version: '3.8'

services:
  agiliate-engine:
    build:
      context: .
    container_name: agiliate-engine
    restart: unless-stopped
    working_dir: /app
    ports:
      - 1337:1337
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bun run start
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  node_modules:
