# Workflow for tests

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: antongolub/action-setup-bun@v1

      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install
        run: bun install

      - name: Run linter
        run: bun lint

      - name: Run tests
        run: bun test
